name: On Main Merge

on:
  push:
    branches:
      - main
      - release
      - ci/ak-node-build
  workflow_dispatch:

permissions:
  id-token: write
  pages: write

jobs:
  # Job 1: Generate the bot token and expose it as a job output.
  generate_token:
    runs-on: ubuntu-latest
    name: Generate Bot Token

    # 🚨 FIX 1: Define an output for this job to store the generated token.
    outputs:
      bot_token_out: ${{ steps.app_token.outputs.token }}

    steps:
      - name: Create GitHu  b App Token
        uses: actions/create-github-app-token@v1
        id: app_token
        with:
          app_id: ${{ secrets.BOT_ID }}
          private_key: ${{ secrets.BOT_SK }}

  on_main_merge:
    needs: generate_tokens
    name: Run On Merge Main Workflow
    uses: algorandfoundation/algokit-shared-config/.github/workflows/on-merge-main.yml@ci/release-workflow
    with:
      NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      BOT_TOKEN: ${{ needs.generate_token.outputs.bot_token_out }}
